language: node_js
node_js:
- node
- 6
- 6.3
- 6.4
- 6.5
- 6.6
- 6.7
- 6.8
- 6.9
- 7
- 7.2
git:
  depth: 1
os: linux
script: npm run start-server
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: tb2garGCI7zxWLTFvjLW7TRqkvB9j3Dacz5S8V6gvF8DU2at32XX9sXwBFIOz4qxuExU3s1mRYUY2WkSjfLlbSPSWaCk58vBPPgHBQP6RRYhI0MOCrI2QMtzYu18EhoTBfIYsK4OVQQDz2zZ5AkGU9tz1q5TXZQizbQQSYoJZO2zQDU2CH4+6XjuGcZJ+vJaZY0twKzJ4PSxHfSBvg8O0OvQf2Y0ks8RLFotLVNSpKubjmAxSsgKZAxWlTX00E8dY9vYlkBFK2x4uLDWjxqfuAUNSyIjcH59hHrUB98V9NAnKW8Vv0dh8sBiEZAw2AHays+p2pBF2kqEtAPnDzcr27LzOn4es/5EhxmYciHhX2Xz9ZenYmq9WNGopx4uOMOZ9vgH/XTulsWsM8MfotKrgkxAusjqml1vV4DevLXoDBd0Ku0sxE0SQjHG+3LnFDvgri+kIvjUgfLmCSqmdCQJ4YRt8Pz6mjnDw4/Jrlv5+2r+HNgBN/FEhCtcMicQjbhMfMdEtThchUaaEO7+8jUUjufhoaAZMbxAXnj7M1zYU1gMAOs6qsunfUltTl861pQ5oQslALMN6jFmhii8aR7IJANkv9dbBp4Vc/7+uWnmZc0rNSSzZfWP8mPu46WhzB2OpeVXFLaFihmr4VdFrqTkatqF1o5oQC34viMspR2sU8E=
