language: node_js
node_js:
  - "6.5.0"
git:
    depth: 1
os: "linux"
script: npm run start-server
cache:
    directories:
        - node_modules
branches:
    only:
        - master
        - production