language: node_js
node_js:
- node
- 6
- 6.3
- 6.4
- 6.5
- 6.6
- 6.7
- 6.8
- 6.9
git:
    depth: 1
os: "linux"
script: npm run start-server
cache:
    directories:
        - node_modules
branches:
    only:
        - master
        - production