language: node_js
node_js:
  - "node"
  - "6.6.0"
  - "4.6.0"
git:
    depth: 1
os: "linux"
script: npm run start-server
cache:
    directories:
        - node_modules
branches:
    only:
        - master
        - production