version: 2
services:
  web:
    image: robototes/robototes-website-web:1bc65f4
    links:
    - mongo
    expose:
    - 3000
    labels:
      io.rancher.scheduler.affinity:host_label: type=private
      io.rancher.container.pull_image: always
    environment:
    - DOMAIN=$DOMAIN
    - G_TRACKING_ID=$G_TRACKING_ID
    - DATABASE_HOST=mongo
    - DATABASE_PORT=27017
  api:
    image: robototes/robototes-website-api:39e47da
    links:
    - mongo
    expose:
    - 3000
    labels:
      io.rancher.scheduler.affinity:host_label: type=private
      io.rancher.container.pull_image: always
    environment:
    - DOMAIN=$DOMAIN
    - TBA_SECRET_KEY=$TBA_SECRET_KEY
    - DATABASE_HOST=mongo
    - DATABASE_PORT=27017
  team:
    image: robototes/robototes-website-team:c04c624
    links:
    - mongo
    expose:
    - 3000
    labels:
      io.rancher.scheduler.affinity:host_label: type=private
      io.rancher.container.pull_image: always
    environment:
    - DOMAIN=$DOMAIN
    - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
    - AUTH0_DOMAIN=$AUTH0_DOMAIN
    - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
    - DATABASE_HOST=mongo
    - DATABASE_PORT=27017
  mongo:
    image: mongo:3.5-jessie
    expose:
    - 27017
    labels:
      io.rancher.scheduler.affinity:host_label: type=private
  lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 443:443
    labels:
      io.rancher.scheduler.affinity:host_label: type=public
