version: 2
catalog:
  name: robototes-website
  version: 2.0.0-alpha
  questions:
  - variable: DOMAIN
    label: The second-level domain that the server resides on
    required: true
    type: string
  - variable: G_TRACKING_ID
    label: The Google analyics tracking ID to report to
    required: false
    type: string
  - variable: TBA_SECRET_KEY
    label: The secret key used to verify the source and integrity of payloads from The Blue Alliance
    required: true
    type: string
  - variable: AUTH0_CLIENT_ID
    label: Auth0 API Client ID
    required: true
    type: string
  - variable: AUTH0_DOMAIN
    label: Auth0 API Domain
    required: true
    type: string
  - variable: AUTH0_CLIENT_SECRET
    label: Auth0 API Client Secret
    required: true
    type: string
  - variable: CERTIFICATE
    label: Origin certificate for load balancer
    required: true
    type: certificate
services:
  web:
    scale: 1
    health_check:
      port: 3000
      request_line: GET / HTTP/1.0
      interval: 2000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
      strategy: recreate
  api:
    scale: 1
    # health_check:
    #   port: 3000
    #   request_line: GET /api/email?alias=test&domain=$DOMAIN HTTP/1.0
    #   interval: 2000
    #   initializing_timeout: 60000
    #   reinitializing_timeout: 60000
    #   unhealthy_threshold: 3
    #   healthy_threshold: 2
    #   response_timeout: 2000
    #   strategy: recreate
  team:
    scale: 1
    health_check:
      port: 3000
      request_line: GET /members HTTP/1.0
      interval: 2000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
      strategy: recreate
  mongo:
    scale: 1
  lb:
    scale: 1
    lb_config:
      port_rules:
      - protocol: https
        hostname: www.$DOMAIN
        source_port: 443
        path: /
        target_port: 3000
        service: web
      - protocol: https
        hostname: www.$DOMAIN
        source_port: 443
        path: /api
        target_port: 3000
        service: api
      - protocol: https
        hostname: www.$DOMAIN
        source_port: 443
        path: /members
        target_port: 3000
        service: team
      certs:
      - $CERTIFICATE
      default_cert: $CERTIFICATE
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
